name: Trigger auto deployment for mcp-toolkit-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mcp-toolkit-app-AutoDeployTrigger-5d0718e5-6c9b-4b5e-abe1-e2843b312c3c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: env-github
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MCPTOOLKITAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MCPTOOLKITAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MCPTOOLKITAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: mcptoolkitacrmcrqsxaxvfqiu.azurecr.io
          registryUsername: ${{ secrets.MCPTOOLKITAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MCPTOOLKITAPP_REGISTRY_PASSWORD }}
          containerAppName: mcp-toolkit-app
          resourceGroup: foundry-resource-ingestion
          imageToBuild: mcptoolkitacrmcrqsxaxvfqiu.azurecr.io/mcp-toolkit-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


